### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by ekianjo** [OtherOfIce/VPN-Jail#2]
OK I tried to run the script with appropriate settings and ovpn configurations (I confirmed before that the ovpn file worked to establish a vpn connection). I get the following errors: 

> cannot resolve host address

while I can ping that address without issue from the terminal. 

> Could not determine IPv4/IPv6 protocol

Then finally:

> Device "tun0" does not exist

while I have tun loaded in my kernel modules. 

Any idea what I may be doing wrong?

**Comment by Dav1dde** [comment]
Most likely openvpn cannot connect because of this line:
```
iptables -t nat -A POSTROUTING -s 10.200.200.0/24 -o en+ -j MASQUERADE #Pass stuff to somthing else ?
```

`en+` means on any interface that starts with `en`, if you're on e.g. `eth0` or any wifi `wl+` the setup won't work.

**Comment by ekianjo** [comment]
so what would be the way to fix this issue?

**Comment by Dav1dde** [comment]
I mean, I wrote how to fix it above...

**Comment by OtherOfIce** [comment]
Fixed some of the issues such as not handling url's and expecting Ethernet.
